0001-clk-sunxi-ng-div-Add-feature-support-to-M-clock-macr.patch
0002-clk-sunxi-ng-sun55i-a523-ccu-Use-M-only-clocks-for-M.patch
0003-clk-sunxi-ng-sun55i-a523-ccu-Use-P-only-clocks-for-h.patch
0004-clk-sunxi-ng-sun55i-a523-r-ccu-Use-P-only-clocks-for.patch
0005-dt-bindings-clk-sun60i-a733-ccu-Add-Allwinner-A733-s.patch
0006-clk-sunxi-ng-sdm-Add-dual-patterns-support.patch
0007-clk-sunxi-ng-a733-Add-PRCM-CCU.patch
0008-clk-sunxi-ng-a733-Add-PLL-clocks-support.patch
0009-clk-sunxi-ng-a733-Add-bus-clocks-support.patch
0010-clk-sunxi-ng-a733-Add-mod-clocks-support.patch
0011-clk-sunxi-ng-a733-Add-bus-clock-gates.patch
0012-clk-sunxi-ng-a733-Add-reset-lines.patch
0013-clk-sunxi-ng-div-add-read-only-operation-support.patch
0014-clk-sunxi-ng-sun6i-rtc-split-main-oscillator-div-and.patch
0015-dt-bindings-rtc-sun6i-add-sun60i-a733-support.patch
0016-clk-sunxi-ng-sun6i-rtc-add-a733-support.patch
0017-pinctrl-sunxi-rename-SUNXI_PINCTRL_NEW_REG_LAYOUT.patch
0018-pinctrl-sunxi-only-use-PortK-special-handling-on-A52.patch
0019-pinctrl-sunxi-refactor-IRQ-register-accessors.patch
0020-pinctrl-sunxi-support-A733-generation-MMIO-register-.patch
0021-dt-bindings-pinctrl-add-compatible-for-Allwinner-A73.patch
0022-pinctrl-sunxi-a523-r-add-a733-r-compatible-string.patch
0023-pinctrl-sunxi-add-support-for-the-Allwinner-A733.patch
0024-dt-bindings-net-sun8i-emac-Add-A733-GMAC210-compatib.patch
0025-net-stmmac-sun55i-Add-per-compatible-match-data.patch
0026-net-stmmac-sun55i-Make-the-delay-step-configurable.patch
0027-net-stmmac-sun55i-Support-TX-delay-extension-bits.patch
0028-net-stmmac-sun55i-Add-support-for-Allwinner-A733-GMA.patch
0029-serial-8250_dw-Keep-the-BUSY-safe-divisor-hook-when-.patch
0030-dt-bindings-serial-snps-dw-apb-uart-Add-Allwinner-A7.patch
0031-serial-8250_dw-Add-Allwinner-A733-UART.patch
0032-dmaengine-sun6i-dma-Refactor-to-support-A733-interru.patch
0033-dmaengine-sun6i-dma-Support-variable-address-widths-.patch
0034-dmaengine-sun6i-dma-Add-num_channels_per_reg-for-fle.patch
0035-dt-bindings-dmaengine-sun50i-a64-dma-Add-allwinner-s.patch
0036-dmaengine-sun6i-dma-Implement-support-for-Allwinner-.patch
0037-mfd-axp20x-Constify-axp313-and-axp717-cells.patch
0038-mfd-axp20x-i2c-Fix-i2c-instantiation.patch
0039-dt-bindings-mfd-x-powers-axp152-Document-AXP318W.patch
0040-mfd-axp20x-Add-support-for-AXP318W-PMIC.patch
0041-regulator-axp20x-add-support-for-the-AXP318W.patch
0042-dt-bindings-i2c-mv64xxx-Add-Allwinner-A733-compatibl.patch
0043-spi-dt-bindings-sun6i-Add-compatibles-for-A733-s-SPI.patch
0044-dt-bindings-irq-sun7i-nmi-Document-the-Allwinner-A73.patch
0045-dt-bindings-mmc-add-Allwinner-A733-compatible.patch
0046-mmc-sunxi-Add-Allwinner-A733-SD-MMC-controller-suppo.patch
0047-thermal-sun8i-Add-Allwinner-A733-Thermal-Sensor-Cont.patch
0048-input-keyboard-sun4i-lradc-keys-Add-Allwinner-A733-s.patch
0049-pwm-sun50i-Add-Allwinner-modern-enhanced-PWM-control.patch
0050-phy-allwinner-Add-Cadence-PCIe-SATA-USB3-Combo-PHY-d.patch
0051-pci-controller-sunxi-Add-Allwinner-A733-DesignWare-P.patch
0052-crypto-allwinner-Add-Crypto-Engine-CE-v5-driver-for-.patch
0053-soc-sunxi-Add-VeriSilicon-VIP9000-NPU-driver-for-All.patch
0054-arm64-dts-allwinner-Add-Allwinner-A733-SoC-and-Orang.patch
0055-arm64-configs-Add-orangepi4pro_defconfig.patch
0056-sunxi-common-Import-Allwinner-platform-updates-from-.patch
